src/Entity/LotHabit.php
<?php

namespace App\Entity;

use App\Repository\LotHabitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LotHabitRepository::class)
 */
class LotHabit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $ReferenceLot;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDepot;

    /**
     * @ORM\Column(type="date")
     */
    private $DateRetrait;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Etat;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="lotHabits")
     */
    private $Client;

    /**
     * @ORM\ManyToMany(targetEntity=TypeHabit::class, inversedBy="lotHabits")
     */
    private $Habit;

    /**
     * @ORM\Column(type="integer")
     */
    private $Prix;

    public function __construct()
    {
        $this->Habit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReferenceLot(): ?string
    {
        return $this->ReferenceLot;
    }

    public function setReferenceLot(string $ReferenceLot): self
    {
        $this->ReferenceLot = $ReferenceLot;

        return $this;
    }

    public function getDateDepot(): ?\DateTimeInterface
    {
        return $this->DateDepot;
    }

    public function setDateDepot(\DateTimeInterface $DateDepot): self
    {
        $this->DateDepot = $DateDepot;

        return $this;
    }

    public function getDateRetrait(): ?\DateTimeInterface
    {
        return $this->DateRetrait;
    }

    public function setDateRetrait(\DateTimeInterface $DateRetrait): self
    {
        $this->DateRetrait = $DateRetrait;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }
    public function __toString()
    {
        $format = "%s \n";
        return sprintf($format, $this->ReferenceLot);
    }

    /**
     * @return Collection|TypeHabit[]
     */
    public function getHabit(): Collection
    {
        return $this->Habit;
    }

    public function addHabit(TypeHabit $habit): self
    {
        if (!$this->Habit->contains($habit)) {
            $this->Habit[] = $habit;
        }

        return $this;
    }

    public function removeHabit(TypeHabit $habit): self
    {
        $this->Habit->removeElement($habit);

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }
}

src/Form/LotHabitType.php
<?php

namespace App\Form;
use App\Entity\TypeHabit;
use App\Entity\LotHabit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class LotHabitType extends AbstractType
{
    protected static $subjects = array('Subject A', 'Subject B', 'Subject C');
    public function buildForm(FormBuilderInterface $builder, array $options)
    
    {
        $builder
            ->add('ReferenceLot')
            ->add('Etat',ChoiceType::class, [
                'choices' => [
                    'Non Laves' =>  'Non Laves' ,
                    'En cours' =>  'En cours',
                    'Finis' => 'Finis',

                ]])
            ->add('Client')
            ->add('DateDepot')
            ->add('DateRetrait')
            ->add('Habit',EntityType::class, [
                'class' => TypeHabit::class,
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('Prix', TextType::class, [
                'data' =>' 1500',
            ])
         
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => LotHabit::class,
        ]);
        
        
    }
}

src/Controller/LotHabitController.php
<?php

namespace App\Controller;

use App\Entity\LotHabit;
use App\Form\LotHabitType;
use App\Repository\LotHabitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/lot/habit")
 */
class LotHabitController extends AbstractController
{
    /**
     * @Route("/", name="lot_habit_index", methods={"GET"})
     */
    public function index(LotHabitRepository $lotHabitRepository): Response
    {
        return $this->render('lot_habit/index.html.twig', [
            'lot_habits' => $lotHabitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="lot_habit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lotHabit = new LotHabit();
        $form = $this->createForm(LotHabitType::class, $lotHabit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lotHabit);
            $entityManager->flush();

            return $this->redirectToRoute('lot_habit_index');
        }

        return $this->render('lot_habit/new.html.twig', [
            'lot_habit' => $lotHabit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lot_habit_show", methods={"GET"})
     */
    public function show(LotHabit $lotHabit): Response
    {
        return $this->render('lot_habit/show.html.twig', [
            'lot_habit' => $lotHabit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="lot_habit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, LotHabit $lotHabit): Response
    {
        $form = $this->createForm(LotHabitType::class, $lotHabit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('lot_habit_index');
        }

        return $this->render('lot_habit/edit.html.twig', [
            'lot_habit' => $lotHabit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lot_habit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, LotHabit $lotHabit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lotHabit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lotHabit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lot_habit_index');
    }
}

templates/lot_habit/_delete_form.html.twig
<form method="post" action="{{ path('lot_habit_delete', {'id': lot_habit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lot_habit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lot_habit/_form.html.twig
 <div class=" container center col-sm-8">
  <fieldset class="container center col-sm-8 border border-secondary"  >
     <legend> <h1> New  Facture</h1></legend>
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="row mb-6">
    <div class="col d-flex justify-content-center">
       <button class="btn ">{{ button_label|default('Save') }}</button>
      </div>
  
    <div class="col">
      <!-- Simple link -->
      <a href="{{ path('lot_habit_index') }}" class="btn " role="button" aria-disabled="true">Back To list</a>
    
    </div>
  </div>
    </fieldset>
        </div>
       

   
 
{{ form_end(form) }}

templates/lot_habit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h1></h1>

    {{ include('lot_habit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('lot_habit_index') }}">back to list</a>

    {{ include('lot_habit/_delete_form.html.twig') }}
{% endblock %}

templates/lot_habit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Facture  {% endblock %}

{% block body %}
    <h1>Facture </h1>

    <table class="table table-bordered ">
        <thead>
            <tr>
                <th>Id</th>
                <th>ReferenceLot</th>
                <th>DateDepot</th>
                <th>DateRetrait</th>
                <th>Etat</th>
                <th>Client</th>
                <td> Prix </td>
                <th>Composant </th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lot_habit in lot_habits %}
            <tr>
                <td>{{ lot_habit.id }}</td>
                <td>{{ lot_habit.ReferenceLot }}</td>
                <td>{{ lot_habit.DateDepot ? lot_habit.DateDepot|date('Y-m-d') : '' }}</td>
                <td>{{ lot_habit.DateRetrait ? lot_habit.DateRetrait|date('Y-m-d') : '' }}</td>
                <td>{{ lot_habit.Etat }}</td>
                <td>{{ lot_habit.Client }}</td>
                  <td>{{ lot_habit.prix }}</td>
                
                 <td> {% for habit in  lot_habit.habit  %}{{ habit.ReferenceHabit }} </br> {% endfor %}</td>
                  
               
                
              
                <td>
                    <a href="{{ path('lot_habit_show', {'id': lot_habit.id}) }}">show</a>
                    <a href="{{ path('lot_habit_edit', {'id': lot_habit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('lot_habit_new') }}">Create new</a>
{% endblock %}

templates/lot_habit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New LotHabit{% endblock %}

{% block body %}
    
    {{ include('lot_habit/_form.html.twig') }}
     
{% endblock %}
  

templates/lot_habit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LotHabit{% endblock %}

{% block body %}
    <h1>LotHabit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lot_habit.id }}</td>
            </tr>
            <tr>
                <th>ReferenceLot</th>
                <td>{{ lot_habit.ReferenceLot }}</td>
            </tr>
            <tr>
                <th>DateDepot</th>
                <td>{{ lot_habit.DateDepot ? lot_habit.DateDepot|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>DateRetrait</th>
                <td>{{ lot_habit.DateRetrait ? lot_habit.DateRetrait|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ lot_habit.Etat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('lot_habit_index') }}">back to list</a>

    <a href="{{ path('lot_habit_edit', {'id': lot_habit.id}) }}">edit</a>

    {{ include('lot_habit/_delete_form.html.twig') }}
{% endblock %}